<?php

class changeDomainUpdateFromGridOptionsProcessor extends modObjectUpdateProcessor
{
    public $objectType = 'changeDomainOptions';
    public $classKey = 'changeDomainOptions';
    public $languageTopics = array('changedomain');
    //public $permission = 'save';


    public function initialize()
    {

        $data = $this->getProperty('data');
        if (empty($data)) {
            return $this->modx->lexicon('invalid_data');
        }
        $data = json_decode($data, true);
        if (empty($data)) {
            return $this->modx->lexicon('invalid_data');
        }
        $this->setProperties($data);
        $this->unsetProperty('data');

        return parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * We doing special check of permission
     * because of our objects is not an instances of modAccessibleObject
     *
     * @return bool|string
     */
    public function beforeSave()
    {
        if (!$this->checkPermissions()) {
            return $this->modx->lexicon('access_denied');
        }

        if (empty($this->getProperty('name'))) {
            return $this->modx->lexicon('changedomain_options_err_empty');
        }
        //Значение опции поменялось

        if($this->getProperty('resource_id') == 0){
            if($this->modx->getCount($this->classKey, array('name' => $this->getProperty('name'), 'id:!=' => $this->getProperty('id'), 'domain_id' => $this->getProperty('domain_id')))){
                return $this->modx->lexicon('changedomain_options_err_ae');
            }
        }else{
            if($this->modx->getCount($this->classKey, array('name' => $this->getProperty('name'), 'id:!=' => $this->getProperty('id'), 'domain_id' => $this->getProperty('domain_id'), 'resource_id' => $this->getProperty('resource_id')))){
                return $this->modx->lexicon('changedomain_options_err_ae');
            }
        }

        return true;

    }


    /**
     * @return bool
     */
    public function beforeSet()
    {
        return parent::beforeSet();
    }
}

return 'changeDomainUpdateFromGridOptionsProcessor';
